---
title: "Project2"
author: "Group 1"
date: "May 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r message=FALSE}
library(AppliedPredictiveModeling)
library(rpart)
library(rpart.plot)
library(tidyverse)
library(DMwR)
library(Hmisc)
library(PerformanceAnalytics)
library(glmnet)
library(ggplot2)
library(caret)
library(nnet)
library(gbm)
dev.new(width = 1280, height = 768 ,units = 'px')
```

## Load Data

```{r}
student_data <- read.csv('C:\\Users\\Nate\\Documents\\DataSet\\StudentData.csv')
```

```{r}
student_data %>% head()
student_data %>% summary()

```

```{r}
for(name in colnames(student_data)){
  if(class(student_data[[name]]) != 'factor'){
  student_data[,name]<- student_data[,name] %>% impute(median)
  student_data[,name]<- student_data[,name] %>% as.numeric()
  }#if
}
student_data %>% summary()
```

```{r}
for(name in colnames(student_data)){
  print(name)  
  print(class(student_data[[name]]))
  if(class(student_data[[name]]) != 'factor'){
  #print(name)  
  #print(class(student_data[[name]]))
  #dev.new()
  print(ggplot(data=student_data, aes(student_data[,name])) + geom_histogram()+xlab(as.character(name)))
  }#if
}
```

```{r}
student_data <- student_data[,-1]
student_data %>% chart.Correlation()
student_data <- student_data %>% preProcess()
student_data %>% head()
```

```{r}
smp_size <- floor(0.8 * nrow(student_data))
library(Metrics)
## set the seed to make your partition reproducible
rmse_values <- vector(mode="numeric", length=0)
for(i in c(1:5)){
  set.seed(i)
  train_ind <- sample(seq_len(nrow(student_data)), size = smp_size)

  train <- student_data[train_ind,]
  test <- student_data[-train_ind,]
  y = train$PH
  x = subset(train, select = -c(PH)) %>% as.matrix()
  lmr <- glmnet(x,y)
  #lmr %>% print()
  #plotcp(anv)
  #rpart.plot(anv)
  #plot(anv)
  test_x <- subset(test, select = -c(PH)) %>% as.matrix()
  pred<- predict(object = lmr, newx = test_x)
  rmse_values[i] <- rmse(test$PH,pred)
}
rmse_values %>% mean()
```

```{r}
rmse_values <- vector(mode="numeric", length=0)
for(i in c(1:5)){
  set.seed(i)
  train_ind <- sample(seq_len(nrow(student_data)), size = smp_size)

  train <- student_data[train_ind,]
  test <- student_data[-train_ind,]
  params_y = subset(train, select = c(PH)) %>% preProcess(method = c('range'))
  y = predict(params_y, subset(train, select = c(PH)))
  x = subset(train, select = -c(PH)) #%>% as.matrix()
  nnet.lm <- nnet(x,y, size =20,entropy = TRUE)
  nnet.lm %>% print()

  test_x <- subset(test, select = -c(PH)) #%>% as.matrix()
  pred<- predict(nnet.lm, newdata = test_x)
  test_params <- subset(test, select = c(PH)) %>% preProcess(method = c('range'))
  test_y <- predict(test_params, subset(test, select = c(PH)))
  rmse_values[i] <- sapply((test_y-pred)^2, mean)
}
rmse_values %>% mean()
```

```{r, rand_tree, eval=TRUE}
# Now I will use a 5x Cross Validation 
rmse_values <- vector(mode="numeric", length=0)
for(i in c(1:5)){
  set.seed(i)
  train_ind <- sample(seq_len(nrow(student_data)), size = smp_size)

  train <- student_data[train_ind,]
  test <- student_data[-train_ind,]
  x = subset(train, select = -c(PH))
  anv <- rpart(
  formula = PH ~ .,
  data    = train,
  method  = "anova"
  )
  anv %>% print()
  plotcp(anv)
  rpart.plot(anv)
  pred<- predict(object = anv, newdata = test)
  rmse_values[i] <- rmse(test$PH,pred)
}

rmse_values %>% mean()
```

```{r, rand_forest, eval=TRUE}
# Now I will use a 5x Cross Validation 
rmse_values <- vector(mode="numeric", length=0)
library(randomForest)
for(i in c(1:5)){
  set.seed(i)
  train_ind <- sample(seq_len(nrow(student_data)), size = smp_size)

  train <- student_data[train_ind,]
  test <- student_data[-train_ind,]
  x = subset(train, select = -c(PH))
  rf.lm <- randomForest(
  formula = PH ~ .,
  data    = train
  )
  rf.lm %>% print()
  plot(rf.lm)
  pred<- predict(object = rf.lm, newdata = test)
  rmse_values[i] <- rmse(test$PH,pred)
}

rmse_values %>% mean()
```

```{r, gbm, eval=TRUE}
# Now I will use a 5x Cross Validation 
rmse_values <- vector(mode="numeric", length=0)
library(randomForest)
for(i in c(1:5)){
  set.seed(i)
  train_ind <- sample(seq_len(nrow(student_data)), size = smp_size)

  train <- student_data[train_ind,]
  test <- student_data[-train_ind,]
  x = subset(train, select = -c(PH))
  gbm.lm <- gbm(
  formula = PH ~ .,
  data    = train,
  distribution = "gaussian" ,
  n.trees = 1250 #determined by incrementing from 100 to 1500 by 150
  )
  gbm.lm %>% print()
  pred<- predict(object = gbm.lm, newdata = test, n.trees = 1250)
  rmse_values[i] <- rmse(test$PH,pred)
}

rmse_values %>% mean()
```
